version: "3"
services:
  test_runner:
    build: .
    image: pytest_runner
    container_name: pytest_runner_works
    environment:
      - ENV=dev
    volumes:
      - .:/test_project/

# docker-compose up --build
#docker-compose rm

